name: UTs & E2E Tests

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs: # Docs: <https://git.io/JvxXE>
  run-ats:
    name: Run the Unit Tests (UTs) and the End-to-End (E2E) Automated Test (AT)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build docker image
        run: >
          docker build
          --file ./Dockerfile
          --tag docker-containers-monitor:local
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg BUILD_VERSION=${{ github.event.release.tag_name }}
          --build-arg VCS_REF=${GITHUB_SHA}
          .

      - name: Try to run container
        run: >
          docker run -d --rm
          -v /var/run/docker.sock:/var/run/docker.sock:ro
          --net=host
          --name docker-containers-monitor
          docker-containers-monitor:local

      - name: Run the Unit Tests (UTs)
        run: docker exec -i docker-containers-monitor sh -c "./run_unit_tests.sh"

      - name: Run the End-to-End (E2E) tests
        run: ./scripts/run_e2e_tests.sh
